### ISSUE TITLE
[General Question] 

### ISSUE THREAD

**Issue by SGDeveloperAcct** [microsoft/axe-windows#481]
Facing memory leak issue when capturing data using test mode
Code used:
CaptureAction.SetTestModeDataContext(ecId.Value, DataContextMode.Test, TreeViewMode.Control, true);

When above code is used to capture data for large web pages memory gets piled up and not released even when Release Data Context is called.

One point machine gets hanged up.

**Comment by SGDeveloperAcct** [comment]
Facing memory leak issue when capturing data using test mode
**Code used:
            CaptureAction.SetTestModeDataContext(ecId.Value, DataContextMode.Test, TreeViewMode.Control, true);**

When above code is used to capture data for large web pages memory gets piled up and not released even when Release Data Context is called.

One point machine gets hanged up.

**Comment by lisli1** [comment]
Thanks for your question. Could you please answer the following questions so we can better understand the issue?

1. Are you using the supported API when this happens? You can find the supported API documented here: https://github.com/microsoft/axe-windows/blob/master/docs/AutomationReference.md. Any interfaces and classes that are not described in that document are unsupported and subject to breaking changes at any time.
2. Are you performing multiple scans from within the same process? 
3. How much memory does it end up using? 
4. Is the memory increasing in the process that's running axe windows or the target application being scanned?
5. It seems like you are trying to scan web pages. In the case of scanning web pages, we recommend using axe-core instead. You can reference [axe-pipelines-samples](https://github.com/microsoft/axe-pipelines-samples) for examples on how to integrate accessibility checking with axe-core in your CI builds. Please let us know if this option would work for you.

**Comment by SGDeveloperAcct** [comment]
1) I've created a windows forms application which will get list of controls on the selected application. Code hooked to button click as follows
            var sa = SelectAction.GetDefaultInstance();
            sa.Select();
            Guid? ecId = sa.GetSelectedElementContextId();
            var ec = GetDataAction.GetElementContext(sa.GetSelectedElementContextId().Value);

            CaptureAction.SetTestModeDataContext(ecId.Value, DataContextMode.Test, TreeViewMode.Control, true);

            if (ec.DataContext != null && ec.DataContext.Elements != null)
            {
            }

            MessageBox.Show("Calling dispose");
            GC.Collect();

2) Yes I'm performing multiple scans on same process
3) Memory shoots up to 2 GB
4) Memory increases for the process that runs Axe.Windows
5) I'm trying to create a windows forms application. I couldn't find a nuget package called Axe.Core for windows forms application

Please help me resolve this.

**Comment by RobGallo** [comment]
@SGDeveloperAcct 
I'm afraid we don't support the interfaces you're using. They are not intended to be used outside the context of Accessibility Insights for Windows.
However, To address your issue, you will need to make sure you manage the objects you create with great care, calling Dispose whenever you are done with an object. My suspicion  is right now you have some axe-windows objects you aren't freeing. Just telling the garbage collector to free up unused memory isn't enough because the garbage collector thinks the objects are still in use.

**Comment by SGDeveloperAcct** [comment]
@RobGallo We are building a small Internal too similar to accessibility insights for testing for which we used this as a reference. Any chance that this method might be removed later?

**Comment by RobGallo** [comment]
@SGDeveloperAcct 
We have no plans right now to remove it. But because it is not part of the supported API, we cannot guarantee it won't be changed sometime.
May I ask why you're creating your own tool rather than using either axe-windows or Accessibility Insights for Windows? Perhaps if we understood your need, it might be something we would want to add to Accessibility Insights. That way, everyone in the community could benefit.
