### ISSUE TITLE
[BUG] Unexpected failures from BoundingRectangle rule

### ISSUE THREAD

**Issue by JGibson2019** [microsoft/axe-windows#571]
**Describe the bug**
Axe.Windows is reporting that "An onscreen element must not have a null BoundingRectangle property" when it's not obvious why.

**To Reproduce**
1. Start the latest version of Windows Debugger (download from https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools)
2. Under "Start debugging", click on the "Attach to process" tab. A list of running processes will be displayed
3. Scan the process using the Axe.Windows CLI
4. Errors are reported, including many that say "An onscreen element must not have a null BoundingRectangle property"

**Expected behavior**
These errors are unexpected since they aren't user focusable and there's no direct user interaction.

**Actual behavior**
The errors show up

**Screenshots or .GIF**
A11ytest file is not included here for privacy reasons. If you need it, contact @DaveTryon 

**Desktop (please complete the following information):**
 - OS: Windows 10 12H2
 - Accessibility Insights for Windows Version: 1.1.1879.1
 - Target Application: WinDbg

**Additional context**
Priority requested -

**Comment by karanbirsingh** [comment]
Assigned to @RobGallo to either add details of requested implementation or to make the change

**Comment by DaveTryon** [comment]
I've spoken with the original reporter, and this doesn't appear to be a rule issue. The code being flagged uses a style trigger that frequently results in an Image control with no image--since there's no image, the control has an empty bounding rectangle but it's still visible. The default [IsOffscreenBehavior](https://docs.microsoft.com/en-us/dotnet/api/system.windows.automation.isoffscreenbehavior?view=windowsdesktop-6.0) is to mirror the visibility state in the IsOffScreen property. The suggested workaround is to add another style trigger to set the control's Visibility property to Visibility.Hidden unless a non-empty image is used. That should cause the __IsOffScreen__ property to return false when the empty image is used.

**Comment by DaveTryon** [comment]
Closing this bug since there's nothing for us to do on it
