### ISSUE TITLE
[BUG] False Positive "An onscreen element must not have a null BoundingRectangle property"

### ISSUE THREAD

**Issue by NCarlsonMSFT** [microsoft/axe-windows#582]
## Describe the bug
When an app has controls that are scrolling off the screen while testing is being done the time between checking IsOnScreen and BoundingRectangle results in a missmatch.

**To Reproduce**
1. Git clone https://github.com/NCarlsonMSFT/ScrollingListBox.git
2. Open the Solution and Ctrl+F5
3. Use Accessibility Insights to test the MainWindow

## Expected behavior
No errors

## Actual behavior
Multiple instances of "An onscreen element must not have a null BoundingRectangle property":
![image](https://user-images.githubusercontent.com/14239288/119206170-405dbd80-ba4f-11eb-97b2-a7074357a80a.png)

## Desktop (please complete the following information):

 - OS: Windows 10 21H1 
 - Accessibility Insights for Windows Version: 1.1.1562.1
 - Original Target Application: Visual Studio 2019
 - Original Target Application Version: 16.9.6

## Additional context
[results.zip](https://github.com/microsoft/axe-windows/files/6525411/results.zip)
This was originally spotted in Visual Studio 2019's Diagnostic Events window for the Service Fabric tools. The referenced WPF app was created for ease of testing.
With the app, when new data is being added you get the test results Scrolling.a11ytest. If you disable the updates you get the results Static.a11ytest in which there are no errors.
The same controls were tested in both cases, but in the former they were moving.

**Comment by DaveTryon** [comment]
@NCarlsonMSFT, you've identified a limitation of the current automated checks, which is that the tests are designed for a static UIA state; the scan results may be inconclusive if the UIA state changes partway through a scan. It might be theoretically possible to start an event listener, then monitor for changes that are within the scope of what we're scanning, and then report that back to the user, but it would be a very involved fix to cover all corner cases in both AIWin and Axe.Windows (since the same issue could impact scan results that originate from the CLI). For the time being, we'll document this limitation and suggest that dynamic elements be in a static state when running automated checks.

Assigning this issue back to you. Please close out at your convenience. Thanks!
