### ISSUE TITLE
[Feature Request] Provide a way for .a11ytest files to be retained even if a scan produces no errors

### ISSUE THREAD

**Issue by renishnair-viper** [microsoft/axe-windows#935]
In IScanner.Scan() method output file of .a11ytest is only created when there is an error.
There is a note added (Note: no output files will be written if no errors were found.)
It should be based on some settings if there is no error but we want to review the file later it is not possible at the moment.
So it should be based on some settings if the user wants a file each time to be generated whether there is an error or not they can set the setting and get the file.
![image](https://github.com/microsoft/axe-windows/assets/110403504/57b82e8f-2d1a-40bc-a55d-5516e768f057)

**Comment by chingucoding** [comment]
Out of curiosity, do you mind me asking what processing you are doing with the a11ytest result file and how it would help having a result even if there were no errors? Is it about the screenshot that is part of it?

**Comment by renishnair-viper** [comment]
We have created an automation unit test case for our project using axe-windows. Suppose we are running the automation unit test every week after development changes and sometimes we encounter an error if we are having the last working file without any error we can compare and keep track of what minor or major changes have affected so we are getting error.

**Comment by DaveTryon** [comment]
I have a diagnostic branch ([see changes](https://github.com/microsoft/axe-windows/compare/main...DaveTryon/diagnose-flaky-integration-test)) that adds this functionality, but it's on the `ConfigBuilder` instead of `IScanner.Scan`. It's not production-ready (it would still need unit tests, documentation, and CLI support), but we'll triage this and see how it lands with respect to other work that our team owns.

**Comment by codeofdusk** [comment]
Released as part of [2.2.0](https://github.com/microsoft/axe-windows/releases/tag/v2.2.0). Closing as complete.
